@baseUrl = http://localhost:3000/api/tasks
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZDkyOWQ4Zi03YmJiLTQ1NmEtYjNjMy1kY2M2YjkyZTkzOTUiLCJlbWFpbCI6ImlydWxAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjYxODcyOTksImV4cCI6MTc2Njc5MjA5OX0.fF8oXJQdUBy0CSdr5pq04BeoF5xh0gR61ajubnDbJ6c

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
   "email": "irul@example.com",
   "password": "irul123654"
}

###
GET {{baseUrl}}?date=2023-12-25
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Meeting Project Re-vamp",
  "description": "Membahas arsitektur database dan integrasi Drizzle ORM",
  "date": "2023-12-25",
  "startTime": "09:00",
  "endTime": "10:30",
  "color": "#3b82f6",
  "tags": ["work", "important", "tech"],
  "reminder": "08:00"
}

###
POST {{baseUrl}}/quick-add
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "command": "Meeting Project MediLink @08:30-10:00"
}