@baseUrl = http://localhost:3000/api/tasks
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZDY5M2FmOC0xMjVkLTQ4MzktYWMyOC0wZjZhZWQ5Mzc1ZTgiLCJlbWFpbCI6ImlydWx4YXJ0YWxAZ21haWwuY29tIiwiaWF0IjoxNzY5MTM5OTQwLCJleHAiOjE3Njk3NDQ3NDB9.dEr9V-9r_6biOfHVBHF4R-j2o_q_zk5onp_xOT5Uusc

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
   "email": "irulxartal@gmail.com",
   "password": "Bedesbanyu2025*"
}

###
GET {{baseUrl}}?date=2023-12-25
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Meeting Project Re-vamp",
  "description": "Membahas arsitektur database dan integrasi Drizzle ORM",
  "date": "2023-12-25",
  "startTime": "09:00",
  "endTime": "10:30",
  "color": "#3b82f6",
  "tags": ["work", "important", "tech"],
  "reminder": "08:00"
}

###
POST {{baseUrl}}/quick-add
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "command": "Meeting Project MediLink @08:30-10:00"
}